"""add new rel between contacts and ads

Revision ID: 729a5ff50258
Revises: f5f5d2ecf65c
Create Date: 2024-09-08 23:50:55.816893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '729a5ff50258'
down_revision: Union[str, None] = 'f5f5d2ecf65c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
