"""added new Table contacts, modified fk's in ads

Revision ID: f5f5d2ecf65c
Revises: f4286c2e41ab
Create Date: 2024-09-05 14:24:43.184593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5f5d2ecf65c'
down_revision: Union[str, None] = 'f4286c2e41ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('by_user', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('telegram', sa.String(length=20), nullable=True),
    sa.Column('phone_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['by_user'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('ads_category_fkey', 'ads', type_='foreignkey')
    op.drop_constraint('ads_by_user_fkey', 'ads', type_='foreignkey')
    op.create_foreign_key(None, 'ads', 'categories', ['category'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'ads', 'users', ['by_user'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ads', type_='foreignkey')
    op.drop_constraint(None, 'ads', type_='foreignkey')
    op.create_foreign_key('ads_by_user_fkey', 'ads', 'users', ['by_user'], ['id'])
    op.create_foreign_key('ads_category_fkey', 'ads', 'categories', ['category'], ['id'])
    op.drop_table('contacts')
    # ### end Alembic commands ###
