
FROM python:3.12

WORKDIR /app/src/back

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY src/back .

ENV PYTHONPATH=/app/src/back

#CMD uvicorn back.main:app --host 0.0.0.0 --port 8000
CMD alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000